#[macro_use]
extern crate alloc;

pub use bincode;
pub use carol_core;
pub use carol_guest_derive::{activate, codec, machine};
pub use serde;
pub use serde_json;
pub use serde_urlencoded;

/// Raw bindings generated by [`wit_bindgen`].
pub mod bind {
    wit_bindgen::generate!({
        world: "machine",
        path: "../../wit/",
        macro_export,
        export_macro_name: "set_machine",
        macro_call_prefix: "carol_guest::bind::",
    });
}

pub mod bls;
mod client;
pub mod http;
pub mod log;
pub mod machines;
pub use client::*;

#[cfg(target_arch = "wasm32")]
mod wasm;
#[cfg(target_arch = "wasm32")]
pub use wasm::*;

#[cfg(not(target_arch = "wasm32"))]
mod not_wasm;
#[cfg(not(target_arch = "wasm32"))]
pub use not_wasm::*;
